# Generated by Django 5.1.3 on 2025-05-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=16, verbose_name="翻译类型")),
                (
                    "projectname",
                    models.CharField(max_length=32, verbose_name="项目名称"),
                ),
                (
                    "description",
                    models.CharField(max_length=256, verbose_name="项目描述"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newApp.userinfo",
                        verbose_name="关联用户",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=1000, verbose_name="原文")),
                ("target", models.CharField(max_length=1000, verbose_name="译文")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newApp.projectinfo",
                        verbose_name="关联项目",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=16, verbose_name="翻译类型")),
                ("origin", models.CharField(max_length=1000, verbose_name="原文")),
                ("target", models.CharField(max_length=1000, verbose_name="译文")),
                ("description", models.CharField(max_length=256, verbose_name="备注")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newApp.projectinfo",
                        verbose_name="关联项目",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TerminologyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=1000, verbose_name="原文")),
                ("target", models.CharField(max_length=1000, verbose_name="译文")),
                ("description", models.CharField(max_length=256, verbose_name="注释")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newApp.projectinfo",
                        verbose_name="关联项目",
                    ),
                ),
            ],
        ),
    ]
