# Generated by Django 5.1.3 on 2025-05-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newApp", "0002_projectinfo_memoryinfo_contentinfo_terminologyinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentinfo",
            name="description",
            field=models.CharField(default="", max_length=256, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="projectinfo",
            name="description",
            field=models.CharField(default="", max_length=256, verbose_name="项目描述"),
        ),
        migrations.AlterField(
            model_name="terminologyinfo",
            name="description",
            field=models.CharField(default="", max_length=256, verbose_name="注释"),
        ),
    ]
