# Generated by Django 5.1.3 on 2025-05-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newApp", "0003_alter_contentinfo_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentinfo",
            name="target",
            field=models.CharField(default="", max_length=1000, verbose_name="译文"),
        ),
    ]
