# Generated by Django 5.1.3 on 2025-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newApp", "0005_alter_contentinfo_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentinfo",
            name="paragraphId",
            field=models.IntegerField(default=1, verbose_name="段号"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectinfo",
            name="projectId",
            field=models.IntegerField(default=1, verbose_name="项目编号"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contentinfo",
            name="target",
            field=models.CharField(default="", max_length=1000, verbose_name="译文"),
        ),
    ]
